spring.application.name=servicefinder

spring.datasource.url=jdbc:mysql://localhost:3306/service_finder_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

